Dsn 14 index page home
MatejFrnka/social-network pull request #7
Opened 2024-02-03 22:23 UTC by yamenchaban

Dsn-14 index page home

2024-02-04 08:55 UTC, patvoj commented
I can see old commits from your previous task in this branch, so I think you mistakenly created this branch out of your previous branch instead of updated Develop branch

2024-02-07 14:32 UTC, bela-riboczki-ext requested changes
As we talked about it, please add this page as a frontend component.

2024-02-09 17:18 UTC, bela-riboczki-ext reviewed
Please review the comments.

2024-02-09 17:18 UTC, bela-riboczki-ext commented on DSN/src/main/resources/images/74130270.png
Can you rename this file to something which has more meaning in the context of the application?
Thank you.

2024-02-09 17:18 UTC, bela-riboczki-ext commented on DSN/frontend/src/app/page.tsx
> +const IndexPage: React.FC = () => {
I think you can export directly this as the content, there is no need to define as a constant here.
Like how it was before in the tutorial's code:
`export default function IndexPage() { * Page contents * }`

2024-02-09 17:42 UTC, yamenchaban commented on DSN/src/main/resources/images/74130270.png
Done
Thank you for your note

2024-02-09 17:42 UTC, yamenchaban commented on DSN/frontend/src/app/page.tsx
> +const IndexPage: React.FC = () => {
Done
Thank you for your note

2024-02-09 18:41 UTC, bela-riboczki-ext approved these changes
Looks good from my side.

2024-02-12 20:45 UTC, patvoj commented on DSN/frontend/src/app/page.tsx
Could you maybe move all files inside a folder beneath app directory? So in this case the root would be something like `src/app/index`. NextJS has automatical routing, so if you have directory structure like this, then you should be able easily open your page by just visiting localhost:port/index
![image](https://github.com/MatejFrnka/social-network/assets/122916872/7dd6ba80-809d-43ae-b0cd-a2a70582c4d2)

NextJS routing: https://nextjs.org/docs/app/building-your-application/routing

2024-02-12 20:45 UTC, patvoj commented on DSN/frontend/src/app/page.tsx
hmm, on the other hand it makes sense to have the main page without anything after domain, so it's only http://localhost:3000 and nothing after that. @bela-riboczki-ext  What do you think?

Besides that I like the old facebook design, and I can see there is already used some area box for posts, so we could maybe used that later

2024-02-13 18:37 UTC, yamenchaban commented on DSN/frontend/src/app/page.tsx
It is a Home Page that should remain without a folder

2024-02-13 20:26 UTC, patvoj commented on DSN/frontend/src/app/page.tsx
Yeah, I realised it's actually correct. So it's alright from my side and I approve this PR

2024-02-13 22:11 UTC, patvoj approved these changes
All good from my side

2024-02-21 17:56 UTC, merged