DSn-15 Registration and login page
MatejFrnka/social-network pull request #9
Opened 2024-02-11 19:34 UTC by patvoj

2024-02-12 14:30 UTC, bela-riboczki-ext requested changes
It's seems there is a lot of rename changes in this pull request. Is it possible that the latest code from develop was not merged? Are these valid renames of the back end files?

Please check my individual comments.

2024-02-12 14:30 UTC, bela-riboczki-ext commented on DSN/frontend/src/app/login/index.html
Can you create this as a react page?
We are losing a lot of features when we have baked in scripts and we just have this as a simple html. Let the next.js combine the elements together.

https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts

2024-02-12 14:30 UTC, bela-riboczki-ext commented on DSN/frontend/src/app/signup/index.html
Can you create this as a react page?
We are losing a lot of features when we have baked in scripts and we just have this as a simple html. Let the next.js combine the elements together.

https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts

2024-02-16 18:41 UTC, patvoj commented
It should be working now. There is one feature I didn't manage to implement and it's auto redirect after successful signup/login. Redirection works with route.push and I have trouble to make this method works.

2024-02-19 09:21 UTC, bela-riboczki-ext approved these changes
Looks good from my side.

2024-02-19 19:42 UTC, pintermate225 approved these changes
I see no issues, good from my side too

2024-02-19 20:06 UTC, merged